site_name: INVOICEtoROefact
site_author: 'Petre Iordanescu, RENware Software Systems, petre.iordanescu@gmail.com'
copyright: 'Copyright (c) RENware Software Systems'




extra:    #NOTE ...ATTN here are components version used as Jinja fields in markdown docs  #FIXME find a way to build them auto at different events like MSI build for example
    xl2roefact_version: "0.1.20"
    web2roefact_version: "n/a"
    xl2roefact_MSI_version: "0.1.19"
    invoice_template_version: "0.1.20"




nav:
    # ---- core functionalities
    - INVOICEtoROefact:
        - Acasa: README.md
        - Componentele sistemului: doc_src/810-DSGN/810.05a-system_components.md
        - xl2roefact: xl2roefact/README.md
        - web2roefact: doc_src/wip.md  #TODO...tbd...
        - xl2roefact PyPi: xl2roefact/doc/README_xl2roefact_library.md
        - invoice template: excel_invoice_template/README.md
    - xl2roefact:
        - Descriere: xl2roefact/README.md
        - License: xl2roefact/LICENSE
    - web2roefact:
        - Descriere: doc_src/wip.md  #TODO...tbd...
    - xl2roefact PyPi:
        - Descriere:  xl2roefact/doc/README_xl2roefact_library.md
        - License: xl2roefact/LICENSE
    - invoice template:
        - Descriere: excel_invoice_template/README.md
        - License: excel_invoice_template/LICENSE
    # ---- support functionalities
    - Help:
        - Manuale de utilizare:
            - Indexul manuale EUMA: doc_src/help/880.30-EUMA_catalog.md
            #NOTE - add here EUMA manuals as needed
        - Manuale de admistrare:
            - Indexul manuale ADMA: doc_src/help/880.30-ADMA_catalog.md
            #NOTE - add here ADMA manuals as needed
        - Cerintele sistemului:
            - Considerente tehnice generale: doc_src/commercial_agreement/110-SRE-general_requirements.md
            - Sistem INVOICEtoROefact: doc_src/commercial_agreement/110-SRE-api_to_roefact_requirements.md
            - Sistem PayValidaBoa: doc_src/commercial_agreement/110-SRE-payments_validation_board_req.uirements.md
            - Specificatii si optiuni tehnice: doc_src/commercial_agreement/agreed_options.md
        - Manual INVOICEtoROefact (PDF): pdfs/print_page.html/print_page.pdf
    # ---- system references
    - About:
        - Despre INVOICEtoROefact: doc_src/wip.md  #TODO `about.md` cu echipa, 2 vorbe "de ce, istoria" etc...
        - Suport: https://www.renware.eu/support.html
        - Contact: https://www.renware.eu/contact.html
        - Cum cumpar: https://www.renware.eu/resources.html#how-to-buy-from-renware
        - Licenta generala sistem: LICENSE  #FIXME see if needed anymore l, first because each component has its own license
        - CHANGELOG sistem: CHANGELOG.md




markdown_extensions:
    - admonition
    - tables
    - mkdocs-typer  #NOTE [0.1.21.post2 240206piu_a] extention to generate Typer apps doc inside a markdown file
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:  #NOTE: [piu] is very important to respect syntax ref `-` character at beginning of items (otherwise not right JSON result !)
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true




#NOTE required to render `mermaid` diagrams
extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - extra-loader.js




plugins:
    - search
    - include-markdown
    - same-dir  #NOTE [piu] plug-in that allow to use markdown files from "root" folder level (where `mkdocs.yml` is located)
    - table-reader  #NOTE [piu] used for static tables rendering from various sources (CSV, JSON, etc as available in Pandas)
    - macros  #NOTE [piu] use external jinja variables and macros (see `https://mkdocs-macros-plugin.readthedocs.io/en/latest/`)
    - markdown-exec  #NOTE [piu] Python execution inside markdown files (execution at build time, "compilation like" NOT dynamically NOT JavaScript)
    - git-revision-date-localized
    # -------------------------- #FIXME [piu] item (`mkdocstrings`) temporary disabled because errs supposing of directory level/position (which is not under doc_src/)
    # - mkdocstrings:  #NOTE to collect docstring(s) from Python code and to embed in markdown as technical documentation
    #     default_handler: python
    #     handlers:
    #         python:
    #         paths: [xl2roefact]
    #                                   #FIXME temporary disabled ------- ALL UP
    # - pdf-export  #NOTE [piu] DO NOT USE this as does not render mermaid in PDF docs
    - print-site:  #NOTE_[piu] IMPORTANT _#NOTE put `print-site` plug in BEFORE `pdf-with-js` in order to works the workaround wit a fake `print_page.md` that will determine generation of 'print_page.pdf' as any other page generated pdf by `pdf-with-js`; ingnore warning ` [mkdocs-print-site] 'print-site' should be defined as the *last* plugin,to ensure...`
        # add_to_navigation: true  #NOTE [piu] not needed here
        # print_page_title: 'Complete INVOICEtoROefact Manual'  #NOTE [piu] not needed here
        add_full_urls: true
        add_table_of_contents: true
    - pdf-with-js:
        enable: true
        #NOTE [piu] all next entries are examples...
        #author:  #NOTE [piu] defaulted from site_author item
        #copyright:  #NOTE [piu] defaulted from copyright item
        #cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true




# provide material for MkDocs theme
theme:
    # language: en  #NOTE [piu] FUTURE FEATURE - should first have a translation...
    logo: doc_src/pictures/api_to_roefact_logo.png
    name: material  #NOTE an alternative is `readthedocs` but more of "visual" features will be "broken / disrupted"
    features:
        - navigation.tabs # left navigation side bar, all level 1 will be shown as top navigation bar
        - navigation.tracking
        - navigation.tabs.sticky
        - navigation.path
        #- toc.integrate  #NOTE [piu] integrates all navigation only in left nav bar
    palette:
        primary: black # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/ for other color options
        accent: blue
    icon:
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left




# directory where start to search or markdown sources
docs_dir: '.'  #NOTE [piu] this works with yhis directory because `mkdocs-same-dir` plug-in

# root directory where to be generated portal
site_dir: './docs' #NOTE: [piu] this is the working directory; final is in `docs/`` which is published through GitHub (chk but @ 230706 petre-dev branch)

# other useful configurations
use_directory_urls: false # allow link between pages to work properly as static site is used offline (ie, as `file:///...`)




# directories to be excludes when build site
#    `docs/` is the directory where site itself will be built (! avoid potential self-ref-recurrence)
exclude_docs: |
  docs/


